### ISSUE TITLE
Set up linting

### ISSUE THREAD

**Issue by ordinaryindustries** [ordinaryindustries/ReviewKit#14]
Set up linting for the framework using [SwiftLint](https://github.com/realm/swiftlint).

**Comment by headStyleColorRed** [comment]
Hey there!
I want to do a couple PR's here for you and I saw in the guidelines that the code should be parsed first with swiftlint. So I might well first start adding it to the project so it highlights by default and maybe even adding it to the commit or push git hooks? So no-one can push to the repo with a faulty-linted-pr?

What do you think?

**Comment by headStyleColorRed** [comment]
Well, it's going to take a while 😅.

I'll create the PR and we can maybe discuss the swiftlint rules (?)

![Screenshot 2024-10-04 at 09 57 45](https://github.com/user-attachments/assets/059f765a-8d94-4eec-a101-9e4cc30a7bdc)

**Comment by headStyleColorRed** [comment]
Here's the PR

https://github.com/ordinaryindustries/ReviewKit/pull/25

**Comment by ordinaryindustries** [comment]
Thank you so much for adding this! I left a question on the PR about dependencies when you get the time.
