### ISSUE TITLE
Rename ShapeProgressView

### ISSUE THREAD

**Issue by ordinaryindustries** [ordinaryindustries/ReviewKit#16]
ShapeProgressView does not describe the view properly. Rename this to something more descriptive that aligns better with the goal of the view. Simply renaming the ShapeProgressView view will likely not be enough. The naming convention propagates down into child views so those need to be renamed as well. Feel free to bring this up in the Discord if you want opinions.

**Comment by yohannescodes** [comment]
I am down for this one 🙌🏾

**Comment by ordinaryindustries** [comment]
Thank you so much!
