### ISSUE TITLE
Display temporary view while rating is being loaded

### ISSUE THREAD

**Issue by ordinaryindustries** [ordinaryindustries/ReviewKit#18]
Currently, the framework assumes the app's rating score is downloaded when the view is displayed. This isn't always the case so we need to handle this. Display a temporary view such as a ProgressView while the rating is loaded. Once the rating is fetched update the rating view to display it.

**Comment by M7md-Ebrahim** [comment]
This is my third attempt at this issue. Sorry for the previous confusion!  #26
