### ISSUE TITLE
Add support for setting foreground style

### ISSUE THREAD

**Issue by ordinaryindustries** [ordinaryindustries/ReviewKit#28]
Add the ability for users to pass a color for the view's text. This should allow them to set a color however they would like and removes the need for us to have to do dynamic text settings based on things like the system color scheme.

**Comment by yohannescodes** [comment]
@ordinaryindustries, can you assign me this issue? I want to try it out and please let me know if there are things I should consider before getting started with it. ✌🏾

**Comment by ordinaryindustries** [comment]
Done! Thank you so much!
