### ISSUE TITLE
Localize in Finnish

### ISSUE THREAD

**Issue by ordinaryindustries** [ordinaryindustries/ReviewKit#31]
Localize the framework in Finnish.

Do not use AI to translate as these are often wrong leading to a poor experience. We want accurate and clear translation. Where possible, use a human with a high level of Finnish experience to translate and proofread. If that is not possible, use a localization service or a tool with a good track record for accurate translation backed by human proof-reading such as the Apple Translate app.

If you have any questions on how to find the localization file or how to implement this please let me know!

**Comment by minna-xD** [comment]
Thank you for this opportunity! 😄 I will gladly provide Finnish translation.

**Comment by minna-xD** [comment]
I want to double check: In the Contributing instructions, it says "Create a new branch for your changes based off the latest release branch." There's "release-2.0", is that the one to use?

**Comment by ordinaryindustries** [comment]
I'm sorry for the confusion. Basing off of main is perfectly fine!
