### ISSUE TITLE
Build all previews

### ISSUE THREAD

**Issue by ordinaryindustries** [ordinaryindustries/ReviewKit#4]
Ensure that all views have previews using the #Preview macro. Consider using things like various device sizes, multiple system appearances, multiple languages, and different view configurations.

**Comment by flash1729** [comment]
I would like to complete this
also if something more is necessary to be done before then do let me know

**Comment by ordinaryindustries** [comment]
It's all yours! Thank you so much for doing this.

**Comment by flash1729** [comment]
@ordinaryindustries please review once
