### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by ordinaryindustries** [ordinaryindustries/ReviewKit#5]
The framework is currently built with English in mind. This limits the framework's usability to only a subsection of the world. Update the app to use localizable strings and catalogs. A great place to get started is in the Apple documentation at https://developer.apple.com/localization/.

**Comment by ordinaryindustries** [comment]
I'm going to start on this so that we can unblock the other localization efforts.

**Comment by ordinaryindustries** [comment]
Fixed in #24

**Comment by minna-xD** [comment]
Hello @ordinaryindustries!
May I do localization for Finnish? I've been searching high and low for projects looking for help in localization this Hacktoberfest.

**Comment by ordinaryindustries** [comment]
Certainly! I created #31 for this. Please leave a comment there so that I can assign it to you. Thank you so much!
